# Generated by Django 5.0.4 on 2024-06-07 18:05

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    Role.objects.create(id=0, name='Admin')
    Role.objects.create(id=1, name='User')
    Role.objects.create(id=2, name='Lecturer')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_active_alter_liketype_active_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
