# Generated by Django 5.0.4 on 2024-06-07 18:09
import random
from django.db import migrations


def create_initial_data(apps, schema_editor):
    role_ids = list(range(0, 3))
    User = apps.get_model('core', 'User')
    User.objects.create_superuser(
        username='admin',
        email='admin@gmail.com',
        password='123'
    )
    User.objects.create_user(first_name='John', last_name='Doe', username='johndoe', password='123',
                        email='john@example.com', role_id=random.choice(role_ids))
    User.objects.create_user(first_name='Jane', last_name='Smith', username='janesmith', password='123',
                        email='jane@example.com', role_id=random.choice(role_ids))
    User.objects.create_user(first_name='Alice', last_name='Johnson', username='alicej', password='123',
                        email='alice@example.com', role_id=random.choice(role_ids))
    User.objects.create_user(first_name='Admin', last_name='User', username='adminfake', password='123',
                        email='admin@example.com', role_id=random.choice(role_ids))
    User.objects.create_user(first_name='Robert', last_name='Anderson', username='rob_anderson', password='123',
                        email='robert@example.com', role_id=random.choice(role_ids))
    User.objects.create_user(first_name='Elizabeth', last_name='Johnson-Smith', username='lizjsmith', password='123',
                        email='elizabeth@example.com', role_id=random.choice(role_ids))
    User.objects.create_user(first_name='Sam', last_name='O\'Connor', username='sam-oconnor', password='123',
                        email='sam@example.com', role_id=random.choice(role_ids))
    User.objects.create_user(first_name='Emily', last_name='Taylor', username='emilytaylor', password='123',
                        email='emily.taylor@example.com', role_id=random.choice(role_ids))
    User.objects.create_user(first_name='Michael', last_name='Brown', username='mikebrown', password='123',
                        email='michael@example.com', role_id=random.choice(role_ids))
    User.objects.create_user(first_name='', last_name='Smith', username='user123', password='123', email='user@example.com',
                        role_id=random.choice(role_ids))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_data'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
