# Generated by Django 5.0.4 on 2024-06-07 18:42

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Tag = apps.get_model('core', 'Tag')
    Tag.objects.create(name='First-year Student')
    Tag.objects.create(name='Second-year Student')
    Tag.objects.create(name='Third-year Student')
    Tag.objects.create(name='Fourth-year Student')
    Tag.objects.create(name='Computer Science Major')
    Tag.objects.create(name='Business Major')
    Tag.objects.create(name='Medical Major')
    Tag.objects.create(name='Student Association Member')
    Tag.objects.create(name='Art Club Member')
    Tag.objects.create(name='Science Enthusiast')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_data'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]


