# Generated by Django 5.0.4 on 2024-06-07 18:44

import random
from django.db import migrations


def create_initial_data(apps, schema_editor):
    post_ids = list(range(1, 11))
    user_ids = list(range(2, 12))
    Comment = apps.get_model('core', 'Comment')
    Comment.objects.create(content='', user_id='', post_id='')
    Comment.objects.create(content='Comment 1 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 2 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 3 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 4 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 5 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 6 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 7 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 8 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 9 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 10 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 11 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 12 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 13 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 14 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 15 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 16 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 17 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 18 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 19 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))
    Comment.objects.create(content='Comment 20 content', user_id=random.choice(user_ids),
                           post_id=random.choice(post_ids))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag_data'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
