# Generated by Django 5.0.4 on 2024-06-13 17:07

from django.db import migrations


def create_default_data(apps, schema_editor):
    Room = apps.get_model('core', 'Room')
    Room.objects.create(title='Facebook')
    Room.objects.create(title='Twitter')
    Room.objects.create(title='Instagram')
    Room.objects.create(title='LinkedIn')
    Room.objects.create(title='Snapchat')
    Room.objects.create(title='TikTok')
    Room.objects.create(title='YouTube')
    Room.objects.create(title='Pinterest')
    Room.objects.create(title='Reddit')
    Room.objects.create(title='WhatsApp')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_room_alter_liketype_image_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_data)
    ]

