# Generated by Django 5.0.4 on 2024-06-12 18:17
import random

from django.db import migrations


def create_default_data(apps, schema_editor):
    user_ids = list(range(2, 12))
    Room = apps.get_model('core', 'Room')
    Room.objects.create(title='Facebook', author_id=random.choice(user_ids))
    Room.objects.create(title='Twitter', author_id=random.choice(user_ids))
    Room.objects.create(title='Instagram', author_id=random.choice(user_ids))
    Room.objects.create(title='LinkedIn', author_id=random.choice(user_ids))
    Room.objects.create(title='Snapchat', author_id=random.choice(user_ids))
    Room.objects.create(title='TikTok', author_id=random.choice(user_ids))
    Room.objects.create(title='YouTube', author_id=random.choice(user_ids))
    Room.objects.create(title='Pinterest', author_id=random.choice(user_ids))
    Room.objects.create(title='Reddit', author_id=random.choice(user_ids))
    Room.objects.create(title='WhatsApp', author_id=random.choice(user_ids))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_liketype_image_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_data)
    ]
