# Generated by Django 5.0.4 on 2024-06-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_room_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinroom',
            unique_together={('user', 'room')},
        ),
    ]
