# Generated by Django 5.0.4 on 2024-06-17 07:31

from django.db import migrations


def create_default_data(apps, schema_editor):
    LikeType = apps.get_model('core', 'LikeType')
    LikeType.objects.create(id=0, name='Like', image='https://res.cloudinary.com/dhitdivyi/image/upload/v1718561961/ptbw4wbdusfztozeffbz.png')
    LikeType.objects.create(id=1, name='Love', image='https://res.cloudinary.com/dhitdivyi/image/upload/v1718611061/o1oawtyr1hrgezlnhunn.png')
    LikeType.objects.create(id=2, name='Sad', image='https://res.cloudinary.com/dhitdivyi/image/upload/v1718611073/odd8bvmfoeejd550fwdb.png')
    LikeType.objects.create(id=3, name='Angry', image='https://res.cloudinary.com/dhitdivyi/image/upload/v1718611086/j2irxvslrfnaeul7tuut.png')
    LikeType.objects.create(id=4, name='Wow', image='https://res.cloudinary.com/dhitdivyi/image/upload/v1718611096/bithtxlvhyfvbifmyv3h.png')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_likepost_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_data)
    ]
