# Generated by Django 5.0.4 on 2024-06-19 06:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_like_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
