# Generated by Django 5.0.4 on 2024-06-20 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_group_notification_joingroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
    ]
